const poolConfig = {
  asset: {
    type: "pool_configurator",
    version: "3.0.0",
    schema: "pbr_webgl_r3f",
    sections: [
      {
        id: "section_pool_shell",
        index: 1,
        name: "Pool Shell & Material",
        defaultOption: "opt_concrete_shotcrete",
        options: [
          {
            id: "opt_concrete_shotcrete",
            name: "Concrete / Shotcrete",
            subtitle: "Light Grey Plaster",
            price: 85000,
            method: "LS",
            color: "#e2e8f0",
            roughness: 0.55,
            metalness: 0.0,
            textureType: "plaster",
            repeat: [1, 1],
          },
          {
            id: "opt_vinyl_liner",
            name: "Vinyl Liner",
            subtitle: "Blue Mosaic Waterliner",
            price: 45000,
            method: "LS",
            color: "#22d3ee",
            roughness: 0.08,
            metalness: 0.05,
            textureType: "mosaic",
            repeat: [1, 1],
          },
        ],
      },
      {
        id: "section_patio_hardscape",
        index: 2,
        name: "Patio Hardscape",
        defaultOption: "opt_concrete_pavers",
        options: [
          {
            id: "opt_concrete_pavers",
            name: "Concrete Pavers",
            subtitle: "Interlocking Grid",
            price: 8.50,
            method: "SF",
            color: "#a8a29e",
            roughness: 0.62,
            metalness: 0.0,
            textureType: "pavers",
            repeat: [12, 12],
          },
          {
            id: "opt_honed_travertine",
            name: "Honed Travertine",
            subtitle: "Natural Ivory Stone",
            price: 16.00,
            method: "SF",
            color: "#e8dcc8",
            roughness: 0.42,
            metalness: 0.0,
            textureType: "travertine",
            repeat: [20, 20],
          },
        ],
      },
      {
        id: "section_water_profile",
        index: 3,
        name: "Water Profile",
        defaultOption: "opt_water_caribbean_cyan",
        options: [
          {
            id: "opt_water_caribbean_cyan",
            name: "Caribbean Cyan",
            subtitle: "Resort Crystal",
            price: 0,
            method: "LS",
            color: "#06b6d4",
            opacity: 0.65,
            distortionScale: 4.0,
            waveSpeed: [0.08, 0.12],
          },
          {
            id: "opt_water_midnight_sapphire",
            name: "Midnight Sapphire",
            subtitle: "Deep Mirror",
            price: 1200,
            method: "LS",
            color: "#1d4ed8",
            opacity: 0.82,
            distortionScale: 3.2,
            waveSpeed: [0.06, 0.09],
          },
        ],
      },
    ],
    dimensions: {
      pool_length: { value: 40, min: 10, max: 100, unit: "ft" },
      pool_width: { value: 20, min: 8, max: 50, unit: "ft" },
      pool_depth: { value: 5, min: 3, max: 12, unit: "ft" },
    },
  },
};

export default poolConfig;
